============================= test session starts =============================
platform win32 -- Python 3.11.7, pytest-8.4.0, pluggy-1.6.0
rootdir: C:\Bachelorarbeit\Translate_Cora
configfile: pytest.ini
plugins: anyio-4.9.0, mock-3.14.1
collected 382 items

cora_python\tests\contSet\ellipsoid\private\test_priv_andHyperplane.py . [  0%]
F

================================== FAILURES ===================================
_______ TestPrivAndHyperplane.test_full_intersection_non_degenerate_2d ________
cora_python\tests\contSet\ellipsoid\private\test_priv_andHyperplane.py:45: in test_full_intersection_non_degenerate_2d
    assert np.isclose(evals[non_zero_eval_idx], 0.5, atol=1e-9) # (radius)^2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   assert False
E    +  where False = <function isclose at 0x0000027A904934B0>(1.0, 0.5, atol=1e-09)
E    +    where <function isclose at 0x0000027A904934B0> = np.isclose
---------------------------- Captured stdout call -----------------------------
[DEBUG] priv_andHyperplane: dist_val = -1.0, E.TOL = 1e-06
============================== warnings summary ===============================
cora_python\tests\contSet\ellipsoid\test_ellipsoid.py:79
  C:\Bachelorarbeit\Translate_Cora\cora_python\tests\contSet\ellipsoid\test_ellipsoid.py:79: PytestUnknownMarkWarning: Unknown pytest.mark.long - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.long

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ===========================
FAILED cora_python/tests/contSet/ellipsoid/private/test_priv_andHyperplane.py::TestPrivAndHyperplane::test_full_intersection_non_degenerate_2d
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!
=================== 1 failed, 1 passed, 1 warning in 20.61s ===================
